version: '3.8'

services:
  mcp-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-entra-auth-server
    ports:
      - "8084:8084"  # MCP server port
      - "8080:8080"  # OAuth callback port
    environment:
      # Microsoft Entra ID Configuration
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      
      # OAuth Configuration
      - OAUTH_CALLBACK_PORT=8080
      - REDIRECT_URI=http://localhost:8080/auth/callback
      - APP_TYPE=confidential
      
      # API Configuration
      - API_SCOPES=${API_SCOPES}
      - BACKEND_API_URL=${BACKEND_API_URL}
      
      # Server Configuration
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8084
      - MCP_TRANSPORT_TYPE=http
      - MCP_SERVER_NAME=entra-auth-server
      - MCP_SERVER_VERSION=1.0.0
      
      # Token Storage
      - TOKEN_CACHE_PATH=/app/data/token_cache.json
    
    volumes:
      # Mount data directory for persistent token storage
      - ./data:/app/data
      # Mount environment file
      - ./.env:/app/.env:ro
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8084', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security
    user: "1000:1000"  # Run as non-root user
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
